### ISSUE TITLE
Set up a prototype online somewhere

### ISSUE THREAD

**Issue by robhawkes** [polygon-city/building-database#40]
Now we've got something that pretty much resembles a proper application, we should get a prototypal version hosted online somewhere for in-situ testing and to use as an example when reaching out to possible building contributors.

**Comment by meetar** [comment]
I've contacted one of our server admins and will try to get the ball rolling in that direction.

**Comment by meetar** [comment]
I've been given some directions for packaging up the app using Vagrant and Chef, which will allow easy deployment on AWS for testing purposes. Eventually imagine we'll want some kind of staging/production setup to support post-launch development.

**Comment by meetar** [comment]
inviting our serverdev @baldur to the org to checkout/troubleshoot the chef/vagrant setp

**Comment by meetar** [comment]
Okay, I have a manually-provisioned VM with the app manually installed here: https://github.com/polygon-city/chef-buildingdb

It seems to be working and I can load the app at http://192.168.x.x:3000 (with my own ip), but I'm unable to login – I suspect some mongodb/vm configuration mismatch.

@baldur has suggested starting the server on 0.0.0.0, but I can't find the location in the config files where that's specified – it appears I should be able to do that in the gruntfile, as per http://stackoverflow.com/questions/19583238/access-node-js-grunt-server-through-localhostport-on-virtual-machine , but I'm not sure where I'd add that – currently planning to reconnect with him on Monday and hack through this.

**Comment by robhawkes** [comment]
I'm looking at this today to connect the missing bits and pieces together. If it doesn't work out of the box then I'm sure it won't take too much to poke it in the right direction – it already looks **a lot** simpler and easier than Docker.

**Comment by robhawkes** [comment]
Ok I've got it all up and running (boy that was a lot of downloads!). Seems to work fine for me, aside from it adding a random user to the database with the wrong schema (I'll look into that), as well as not shutting down properly (`ctrl+c` hangs on "default: Waiting for cleanup before exiting...").

**Comment by robhawkes** [comment]
I'm currently unable to connect to the Mongo database from outside of Vagrant, though this might be because Mongo doesn't allow remote connections by default ([possible fix here](http://stackoverflow.com/questions/28002848/failing-to-connect-to-remote-mongodb-server)).

**Comment by robhawkes** [comment]
There's a bug with the upload process crashing the app when you try to upload a building. I need to look into this error further, though it looks like an issue with the model-converter trying to spawn a child process for `assimp`:

```
==> default: events.js:72
==> default:         throw er; // Unhandled 'error' event
==> default:
==> default:
==> default:
==> default:
==> default:
==> default:
==> default:
==> default:
==> default:
==> default:      ^
==> default: Error: spawn ENOENT
==> default:     at errnoException (child_process.js:988:11)
==> default:     at Process.ChildProcess._handle.onexit (child_process.js:779:34)
```

On a related note, I'll also look at running the Node process in debug mode so we can get some useful output.

**Comment by meetar** [comment]
I was having these same errors and assumed it was a configuration problem – I'm scheduled to look over this today with one of our systems engineers to troubleshoot it and then convert it to a Chef setup for upload to AWS.

**Comment by robhawkes** [comment]
I think it might be even simpler than I thought actually, I don't think `assimp` is even installed! I never got round to making a pre-compiled binary for Linux so it needs to be installed manually. [This is how I had it set up for Docker](https://github.com/polygon-city/building-database/blob/docker/Dockerfile#L14).

**Comment by robhawkes** [comment]
Watching the build process I see that there are some other bits we can tidy up on, such as:

```
==> default: + sudo mkdir /root/.ssh
==> default: mkdir:
==> default: cannot create directory ‘/root/.ssh’
==> default: : File exists
```

and

```
==> default: + git clone git@github.com:polygon-city/building-database.git
==> default: fatal: destination path 'building-database' already exists and is not an empty directory.
```

**Comment by robhawkes** [comment]
I've fixed the crash on upload but forcing `assimp` to be installed – I'll push that change with some others later today.

**Comment by robhawkes** [comment]
I've pushed some tweaks and the `assimp` update with 5bd343a. It's all working on my machine so far, you just need to register normally through the app first, and manually set that user to an admin if you want to try that side of things. To do that run `vagrant ssh`, then `mongo`, and then the following Mongo command:

```
db.users.update({username: "YOUR_USERNAME"}, {$set: {group: "admin"}});
```

**Comment by meetar** [comment]
I've got a starter chef configuration taken as far as downloading the buildingdb repo, setting up the mongo db, and generating the db config file, here: https://github.com/polygon-city/chef-buildingdb/tree/chef

I haven't got the node app to actually start yet, but @baldur says he'll be taking another look at it soon.

**Comment by meetar** [comment]
We have an updated chef setup at https://github.com/polygon-city/chef-buildingdb/tree/chef and once the vm is up I can connect to the app at http://192.168.10.10:3000/ - the provisioning setup still doesn't run the db setup script, and even if I run that manually I'm still having db issues (can't sign up or log in, so can't upload any buildings) but I can't tell at this point whether that's chef or the buildingdb code. I've filed an issue about the signup crash here: https://github.com/polygon-city/building-database/issues/63

**Comment by robhawkes** [comment]
Awesome! Let me know when you guys have it set up from your point of view (ie. the db setup, etc) and I'll give it a once-over. I'm assuming this will help quite a lot for doing testing with #57.

**Comment by meetar** [comment]
We have a working chef install here: https://github.com/polygon-city/chef-buildingdb/tree/chef
@robhawkes, give it a try and see if it works for you? Just clone the repo and `vagrant up`

**Comment by robhawkes** [comment]
Nice! My Internet is horrifically slow so it's taking a while to download the dependencies but I'll let you know how I get on.

**Comment by robhawkes** [comment]
I've had a go at this and followed the instructions on the repo too, though I've hit this error after `vagrant up`:

```
Shared folders that Chef requires are missing on the virtual machine.
This is usually due to configuration changing after already booting the
machine. The fix is to run a `vagrant reload` so that the proper shared
folders will be prepared and mounted on the VM.
```

I've tried `vagrant reload` to no avail. I'll have a proper look tomorrow and see what I can find.

**Comment by robhawkes** [comment]
I managed to get a bit further but nothing was accessible via http://127.0.0.1:3000. I've tried to run `vagrant halt` and `vagrant up` but then the above error comes back.

**Comment by robhawkes** [comment]
This is as far as I can get when I clear the Vagrant cache to fix the shared folders error:

```
==> default: Running chef-solo...
==> default: stdin: is not a tty
==> default: [2015-02-19T09:11:35+00:00] INFO: Forking chef instance to converge...
==> default: [2015-02-19T09:11:35+00:00] WARN:
==> default: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
==> default: SSL validation of HTTPS requests is disabled. HTTPS connections are still
==> default: encrypted, but chef is not able to detect forged replies or man in the middle
==> default: attacks.
==> default:
==> default: To fix this issue add an entry like this to your configuration file:
==> default:
==> default: ```
==> default:   # Verify all HTTPS connections (recommended)
==> default:   ssl_verify_mode :verify_peer
==> default:
==> default:   # OR, Verify only connections to chef-server
==> default:   verify_api_cert true
==> default: ```
==> default:
==> default: To check your SSL configuration, or troubleshoot errors, you can use the
==> default: `knife ssl check` command like so:
==> default:
==> default: ```
==> default:   knife ssl check -c /tmp/vagrant-chef/solo.rb
==> default: ```
==> default:
==> default: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
==> default: [2015-02-19T09:11:35+00:00] INFO: *** Chef 11.12.8 ***
==> default: [2015-02-19T09:11:35+00:00] INFO: Chef-client pid: 1423
==> default: [2015-02-19T09:11:43+00:00] INFO: Setting the run_list to ["recipe[buildingdb::default]"] from CLI options
==> default: [2015-02-19T09:11:43+00:00] INFO: Run List is [recipe[buildingdb::default]]
==> default: [2015-02-19T09:11:43+00:00] INFO: Run List expands to [buildingdb::default]
==> default: [2015-02-19T09:11:43+00:00] INFO: Starting Chef Run for buildingdb
==> default: [2015-02-19T09:11:43+00:00] INFO: Running start handlers
==> default: [2015-02-19T09:11:43+00:00] INFO: Start handlers complete.
==> default: [2015-02-19T09:11:44+00:00] WARN: Cloning resource attributes for template[/etc/mongodb.conf] from prior resource (CHEF-3694)
==> default: [2015-02-19T09:11:44+00:00] WARN: Previous template[/etc/mongodb.conf]: /tmp/vagrant-chef/d1724300d9c9e942a4af6efe1adad38e/cookbooks/mongodb/recipes/install.rb:14:in `from_file'
==> default: [2015-02-19T09:11:44+00:00] WARN: Current  template[/etc/mongodb.conf]: /tmp/vagrant-chef/d1724300d9c9e942a4af6efe1adad38e/cookbooks/mongodb/definitions/mongodb.rb:139:in `block in from_file'
==> default: [2015-02-19T09:11:44+00:00] WARN: Cloning resource attributes for execute[mongodb-systemctl-daemon-reload] from prior resource (CHEF-3694)
==> default: [2015-02-19T09:11:44+00:00] WARN: Previous execute[mongodb-systemctl-daemon-reload]: /tmp/vagrant-chef/d1724300d9c9e942a4af6efe1adad38e/cookbooks/mongodb/recipes/install.rb:37:in `from_file'
==> default: [2015-02-19T09:11:44+00:00] WARN: Current  execute[mongodb-systemctl-daemon-reload]: /tmp/vagrant-chef/d1724300d9c9e942a4af6efe1adad38e/cookbooks/mongodb/definitions/mongodb.rb:174:in `block in from_file'
==> default: [2015-02-19T09:11:44+00:00] WARN: Cloning resource attributes for template[/etc/init/mongodb.conf] from prior resource (CHEF-3694)
==> default: [2015-02-19T09:11:44+00:00] WARN: Previous template[/etc/init/mongodb.conf]: /tmp/vagrant-chef/d1724300d9c9e942a4af6efe1adad38e/cookbooks/mongodb/recipes/install.rb:42:in `from_file'
==> default: [2015-02-19T09:11:44+00:00] WARN: Current  template[/etc/init/mongodb.conf]: /tmp/vagrant-chef/d1724300d9c9e942a4af6efe1adad38e/cookbooks/mongodb/definitions/mongodb.rb:180:in `block in from_file'
==> default: [2015-02-19T09:11:44+00:00] WARN: Cloning resource attributes for service[nginx] from prior resource (CHEF-3694)
==> default: [2015-02-19T09:11:44+00:00] WARN: Previous service[nginx]: /tmp/vagrant-chef/d1724300d9c9e942a4af6efe1adad38e/cookbooks/nginx/recipes/service.rb:1:in `from_file'
==> default: [2015-02-19T09:11:44+00:00] WARN: Current  service[nginx]: /tmp/vagrant-chef/d1724300d9c9e942a4af6efe1adad38e/cookbooks/nginx/recipes/default.rb:69:in `from_file'
==> default:       ** Notice: The native BSON extension was not loaded. **
==> default:
==> default:       For optimal performance, use of the BSON extension is recommended.
==> default:
==> default:       To enable the extension make sure ENV['BSON_EXT_DISABLED'] is not set
==> default:       and run the following command:
==> default:
==> default:         gem install bson_ext
==> default:
==> default:       If you continue to receive this message after installing, make sure that
==> default:       the bson_ext gem is in your load path.
==> default: [2015-02-19T09:11:45+00:00] INFO: Created or updated user builder on building-database
==> default: [2015-02-19T09:11:46+00:00] INFO: package[ncurses-dev] is a virtual package, actually acting on package[libncurses5-dev]
==> default: [2015-02-19T09:11:51+00:00] INFO: ruby_block[buildingdb before_deploy] called
==> default: [2015-02-19T09:12:02+00:00] INFO: Chef Run complete in 19.209835241 seconds
==> default: [2015-02-19T09:12:02+00:00] INFO: Running report handlers
==> default: [2015-02-19T09:12:02+00:00] INFO: Report handlers complete
```

**Comment by meetar** [comment]
I believe that's a success! The site should be visible at http://192.168.10.10 – my apologies for neglecting to mention the updated IP in the instructions, I've added it to the readme for reference.

**Comment by robhawkes** [comment]
Aha! Yeah that works with the new URL, thanks.

Interestingly, the URL reported by the app using `req.headers.host` is 127.0.0.1 so none of the verification links work. I suppose the 192.168.10.10 URL is an external interface to the local Vagrant system (which could be 127.0.0.1). We'll need to work out a good way to report the correct URL, or just add it to the config file manually.

For my own future reference, [this is how to fix](req.headers.host) the Vagrant shared folders error:

```
rm .vagrant/machines/default/virtualbox/synced_folders
vagrant reload --provision
```

**Comment by robhawkes** [comment]
It looks like the Chef repo is up and running ok so I'm going to close this and we can track any issues with it in there.
